services:
  chat-tts-ui:
    image: 192.168.0.96:5000/cyberfantasy2024/chattts:202406
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: chat-tts-ui
    restart: always
    volumes:
      - "./:/app"
    ports:
      - 9966:9966
    user: "${UID}:${GID}"
    environment:
      LOG_LEVEL: DEBUG
      WEB_ADDRESS: 0.0.0.0:9966
      NVIDIA_VISIBLE_DEVICES: all
    command: python3 app.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
